from . import erp_employee_inherit
from . import other_project_history
from . import academic_qualification
from . import work_experience
from . import erp_certification
from . import erp_training
from . import tech_skill
from . import bjit_project_history
from . import employee_edit
